title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://lizannep.github.io/

aux_links:
  Linkedin: https://www.linkedin.com/in/pan-l-366164289/
