title: Pan's Place
description: My personal website showcasing projects, blogs, and contact info.
theme: just-the-docs

url: https://lizannep.github.io

aux_links:
  Linkedin: https://www.linkedin.com/in/pan-l-366164289/
  GitHub: https://github.com/lizannep
  Blog: /blog/

